### ISSUE TITLE
Provide documentation for the Asset Services on a per-service basis

### ISSUE THREAD

**Issue by senakafdo** [ove/ove-asset-services#20]
There are couple of challenges right now, around where to set the credentials and how to run the new Docker build, which was the basis of creating this issue. But, we also need to explain:
1. What each service does
2. How to configure each service (S3 details, hostnames etc).
3. How to setup and configure the dependencies (MariaDB, ObjectStore etc) and instructions on how to use alternative DBs (SQL Server, SQLite, Postgres, etc) or object stores.
4. How to find the configuration parameters for each service (i.e. link to S3 docs on where in S3 you can find access key, secret etc)
5. How the UI works
6. How to use the APIs to obtain locations of where assets were uploaded (along with sample curl commands for Linux/Mac and Windows environments)

**Comment by senakafdo** [comment]
Important details on running ove-asset-services until this issue and #29 are resolved:
1. The `AssetManagerHost` (will be renamed to `AssetManagerHostUrl` when #26 is fixed) and `ServiceHostUrl` should use <IP>:<Port> or <Hostname>:<Port>, localhost does not work.
2. The port for `AssetManagerHost` (or `AssetManagerHostUrl` in the future) is 8181. The port for the ServiceHostUrl changes according to the service (ex:- for Images Tiles it is 8182).
3. S3 Client's Service URL must end with a `/` until #29 is resolved.

If there are issues running the containers, it could also be down to the Docker environment having specific issues or previous images having improper settings. Cleaning up Docker (and worst case reinstalling it completely) will help resolve these issues.

**Comment by davidbirchwork** [comment]
Please see https://github.com/ove/ove-asset-services/pull/35

**Comment by davidbirchwork** [comment]
fixed in #35
