### ISSUE TITLE
Images not processed when running OVE Asset Services with Docker

### ISSUE THREAD

**Issue by senakafdo** [ove/ove-asset-services#24]
Steps to reproduce:
1. Edit the docker-compose.yml inside each individual asset service and set the environment variables such as S3 Client Access keys, secret etc.
2. Build each individual asset service running the `./build.sh`
3. Run each individual asset service using `export SERVICE_VERSION=latest; docker-compose -f docker-compose.yml up -d`
4. Navigate to http://localhost:8181/OVEAssetModelController/Create and upload a new image. It remains indefinitely in the Unprocessed state.

This issue is blocking the successful testing of many pull requests that have been submitted and therefore delays their approval.

**Comment by senakafdo** [comment]
Upon testing further I figured that this was down to using localhost:8181 and the container internally running on :80 and not 8181. This is a change from how these services used to work previously (based on settings in appsettings.json). After changing the ports to MY_IP:8181, the Image Tiles Service successfully registers with the Asset Manager and the images are processed. However, it now ends up in a error state with the error:

`System.UriFormatException: Invalid URI: Invalid port specified.   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)   at System.Uri..ctor(String uriString)   at OVE.Service.ImageTiles.Domain.ASyncImageProcessor.DownloadAsset(String url, OVEAssetModel asset) in /usr/src/app/src/OVE.Service.ImageTiles/Domain/ASyncImageProcessor.cs:line 220   at OVE.Service.ImageTiles.Domain.ASyncImageProcessor.ProcessImage(Object state) in /usr/src/app/src/OVE.Service.ImageTiles/Domain/ASyncImageProcessor.cs:line 86`

It would be best to know the exact URL combinations used for `AssetManagerHost` and `ServiceHostUrl` when this worked properly.

**Comment by senakafdo** [comment]
Alright, issue resolved, :). It was nothing specific to the setup. It seemed to be something specific to my Docker installation. I upgraded and deleted and recreated the entire build based instructions on SO and it resolved it. I will proceed to testing the aggregate builds and resolve that issue as well.

**Comment by davidbirchwork** [comment]
Glad to hear this is working :)

I will add documentation to this repo soon
