### ISSUE TITLE
/api/ServicesRegistry/GetService returns details of non-existing Graph Service

### ISSUE THREAD

**Issue by senakafdo** [ove/ove-asset-services#25]
If someone only starts the Asset Manager with the ImageTiles service, they should not see details about the non-existing Graph service. The services should ideally be registering themselves with the Asset Manager, according to the design of it.

**Comment by davidbirchwork** [comment]
This applies both to the Image and Graph entries in appsettings.json - both should be removed as they will be filled when another service registered. 

However removing all service registrations will cause the asset manager to be non functional as you will not be able to upload anything as there are no services to choose. 

Hence i have appended this to https://github.com/ove/ove-asset-services/pull/15 which will permit users to upload zip files even if no other services are running

**Comment by senakafdo** [comment]
Yup, makes sense, and we can resolve both issues in a single PR.

**Comment by davidbirchwork** [comment]
fixed in PR #15
