### ISSUE TITLE
[Image Tiles Service] Consistency bug: AssetManagerHost vs ServiceHostUrl in appsettings.json

### ISSUE THREAD

**Issue by senakafdo** [ove/ove-asset-services#26]
We should have either `AssetManagerHost` and `ServiceHost` or `AssetManagerHostUrl` and `ServiceHostUrl`.

**Comment by senakafdo** [comment]
Fixed in PR #27.

**Comment by davidbirchwork** [comment]
lol not much point assigning me these issues if they are opened, assigned, a fixed committed and merged over a weekend before i get to see them ;)

thanks for the code improvement @senakafdo
