### ISSUE TITLE
Ending slash in urls should not be mandatory (e.g. s3Client -> ServiceURL, etc.)

### ISSUE THREAD

**Issue by senakafdo** [ove/ove-asset-services#29]
A simple util to add the slash at the end if it does not exist will make things much easier for users.

**Comment by davidbirchwork** [comment]
fixed in https://github.com/ove/ove-asset-services/pull/30

**Comment by oserban** [comment]
These includes:

- ServiceHostUrl
- s3Client__ServiceURL
- AssetManagerHostUrl

**Comment by davidbirchwork** [comment]
updated these cases
