### ISSUE TITLE
Rename Repo

### ISSUE THREAD

**Issue by davidbirchwork** [ove/ove-asset-services#3]
I suggest this repo is called ove-asset-services since it contains more than just an asset manager but services which support working with assets.

**Comment by davidbirchwork** [comment]
@senakafdo agreed, I don't want a new repo, let us just change the name of this repo to reflect that this repo contains more than just the asset manager. "ove-asset-services" makes sense as once service is the UI, others actually process assets.

**Comment by davidbirchwork** [comment]
(to avoid confusion with ove-services I wonder if that shouldn't be called ove-core-services) ?

**Comment by senakafdo** [comment]
Name of this repo is changed, as we have already discussed and agreed as to why ove-services is not called ove-core-services, will keep it as is.
