### ISSUE TITLE
The image tile service should not die if the registration procedure fails 

### ISSUE THREAD

**Issue by oserban** [ove/ove-asset-services#32]
If the tile service started faster than the asset manager, the tile service dies and gets restarted by pm2.

I think a better approach is to sleep for x ms and then retry, making y attempts to register. It makes the whole ecosystem more stable and less error prone on bootup.

**Comment by davidbirchwork** [comment]
I've proposed a fix in https://github.com/ove/ove-asset-services/pull/37 but am interested to know whether people are happy with this
