### ISSUE TITLE
Change filename validation to url encoding

### ISSUE THREAD

**Issue by davidbirchwork** [ove/ove-asset-services#4]
as requested by @DavidAkroyd

**Comment by senakafdo** [comment]
Point being that existing validation (losely based on the [bucket name restrictions](https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html) are very restrictive and not required according to the [object key naming best practices](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html).

**Comment by davidbirchwork** [comment]
Following discussion with @DavidAkroyd we agreed to relax the restrictions on the validation but to keep them fairly tight because we are supporting a number of operating systems and platforms. This also avoids pushing the pressure of supporting strange filenames onto other components of OVE.

**Comment by davidbirchwork** [comment]
please see https://github.com/ove/ove-asset-services/pull/14

**Comment by davidbirchwork** [comment]
fixed in #14
