### ISSUE TITLE
Potentially unwanted Thread.Sleep(3000) in code

### ISSUE THREAD

**Issue by senakafdo** [ove/ove-asset-services#42]
As discussed with @davidbirchwork this seems to be a wait to avoid a directory not being created on time for use by external services. But the operation used is documented as a synchronous operation and therefore, a wait should not be required. However, there may be something else that leads to this which can be dealt with in some other way.

**Comment by davidbirchwork** [comment]
As discussed I will remove this sleep and whatever issue it supressed may or may not resurface.
I suspect it will not given how much we have modified the docker file.

**Comment by senakafdo** [comment]
@davidbirchwork, I can confirm that there is no functionality difference with or without the proposed fix. I have approved the PR.
