### ISSUE TITLE
Docker build instructions are inaccurate

### ISSUE THREAD

**Issue by senakafdo** [ove/ove-asset-services#51]
Currently we have `Alternatively, you can use docker. Each package has its own docker image, which can be build by executing the build script or docker-compose directly.`

However, we don't use `docker-compose` at all within this project, and we also do not provide instructions on how to run the build scripts. It is probably worth to note that linux tools need to be installed in windows environments in order to run these build scripts.

**Comment by oserban** [comment]
What needs to be done here is to document better the docker-compose build steps + how to set the system variable.

**Comment by senakafdo** [comment]
This is fixed in e49cb3b.
